// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyManagement.Infrastructure.Persistence;

#nullable disable

namespace PolicyManagement.Infrastructure.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    partial class PolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyManagement.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("FlaggedForReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("flagged_for_review");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("line_of_business");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("policy_number");

                    b.Property<string>("PolicyholderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("policyholder_name");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("premium_amount");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Underwriter")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("underwriter");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Policies_CreatedAt")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_Policies_EffectiveDate")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_Policies_ExpiryDate")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("FlaggedForReview")
                        .HasDatabaseName("IX_Policies_FlaggedForReview")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("LineOfBusiness")
                        .HasDatabaseName("IX_Policies_LineOfBusiness")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Policies_PolicyNumber");

                    b.HasIndex("PolicyholderName")
                        .HasDatabaseName("IX_Policies_PolicyholderName")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Policies_Region")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Policies_Status")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("ExpiryDate", "Status")
                        .HasDatabaseName("IX_Policies_ExpiryDate_Status")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("Status", "LineOfBusiness")
                        .HasDatabaseName("IX_Policies_Status_LineOfBusiness")
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("Status", "Region")
                        .HasDatabaseName("IX_Policies_Status_Region")
                        .HasFilter("is_deleted = 0");

                    b.ToTable("Policies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
